"""empty message

Revision ID: 0261a77846f0
Revises: f7e429e4f539
Create Date: 2020-05-29 16:52:00.573393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0261a77846f0'
down_revision = 'f7e429e4f539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('REVIEW', sa.Column('review_type', sa.Enum('FROM_HOSTS', 'FROM_GUESTS', name='reviewtype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('REVIEW', 'review_type')
    # ### end Alembic commands ###
