"""empty message

Revision ID: 057e8704e95c
Revises: 0261a77846f0
Create Date: 2020-05-29 16:52:47.162627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057e8704e95c'
down_revision = '0261a77846f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('REVIEW', sa.Column('review_type', sa.Enum('FROMHOSTS', 'FROMGUESTS', name='reviewtype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('REVIEW', 'review_type')
    # ### end Alembic commands ###
