"""empty message

Revision ID: 08c602cc53f5
Revises: 9d7179baafb6
Create Date: 2020-05-21 12:38:29.139381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c602cc53f5'
down_revision = '9d7179baafb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TOUR', sa.Column('location_id', sa.Integer(), nullable=False))
    op.drop_constraint('TOUR_location_fkey', 'TOUR', type_='foreignkey')
    op.create_foreign_key(None, 'TOUR', 'LOCATION', ['location_id'], ['id'])
    op.drop_column('TOUR', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TOUR', sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'TOUR', type_='foreignkey')
    op.create_foreign_key('TOUR_location_fkey', 'TOUR', 'LOCATION', ['location'], ['id'])
    op.drop_column('TOUR', 'location_id')
    # ### end Alembic commands ###
