"""empty message

Revision ID: 1172debb49f0
Revises: c2c8170be46f
Create Date: 2020-05-26 22:01:04.893582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1172debb49f0'
down_revision = 'c2c8170be46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TOUR', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TOUR', 'image_url')
    # ### end Alembic commands ###
