"""empty message

Revision ID: 18519d708a84
Revises: 7d9428c9eb84
Create Date: 2020-04-01 14:19:52.687727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18519d708a84'
down_revision = '7d9428c9eb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TOUR', sa.Column('category', sa.Enum('ANIMALS', 'BEACH', 'HIKING', 'FOOD AND DRINK', 'CITY', name='tour_category'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TOUR', 'category')
    # ### end Alembic commands ###
