"""empty message

Revision ID: 1da7a2dc7463
Revises: b7f7281da90d
Create Date: 2020-04-01 14:15:22.611802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da7a2dc7463'
down_revision = 'b7f7281da90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TOUR', sa.Column('category', sa.Enum('ANIMALS', 'BEACH', 'FOODANDDRINK', 'HIKING', 'CITY', name='tourcategory'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TOUR', 'category')
    # ### end Alembic commands ###
