"""empty message

Revision ID: 1eb2c380e310
Revises: 3f5a6fc0f88b
Create Date: 2020-05-29 15:00:30.121075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb2c380e310'
down_revision = '3f5a6fc0f88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('banner', sa.String(length=60), nullable=True))
    op.add_column('USER', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'USER', 'LOCATION', ['location_id'], ['id'])
    op.drop_column('USER', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'USER', type_='foreignkey')
    op.drop_column('USER', 'location_id')
    op.drop_column('USER', 'banner')
    # ### end Alembic commands ###
