"""empty message

Revision ID: 3a67ed97afe3
Revises: 7eb51b46f787
Create Date: 2020-03-31 16:24:25.144116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a67ed97afe3'
down_revision = '7eb51b46f787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('mobile', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USER', 'mobile')
    # ### end Alembic commands ###
