"""empty message

Revision ID: 3f5a6fc0f88b
Revises: 5f81c734f711
Create Date: 2020-05-28 21:28:20.376002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5a6fc0f88b'
down_revision = '5f81c734f711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TOUR', sa.Column('equipment', sa.Text(), nullable=True))
    op.add_column('TOUR', sa.Column('itinerary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TOUR', 'itinerary')
    op.drop_column('TOUR', 'equipment')
    # ### end Alembic commands ###
