"""empty message

Revision ID: 4c56929a47a3
Revises: 2a78abfc1c9f
Create Date: 2020-04-03 13:30:00.369412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c56929a47a3'
down_revision = '2a78abfc1c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('customer_rating_count', sa.Integer(), nullable=False))
    op.add_column('USER', sa.Column('guide_rating_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USER', 'guide_rating_count')
    op.drop_column('USER', 'customer_rating_count')
    # ### end Alembic commands ###
