"""empty message

Revision ID: 65691213a42f
Revises: 3a67ed97afe3
Create Date: 2020-03-31 16:44:18.082377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65691213a42f'
down_revision = '3a67ed97afe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USER', 'age')
    # ### end Alembic commands ###
