"""empty message

Revision ID: 66aa60d037af
Revises: 1b0976cbe4ad
Create Date: 2020-04-01 14:22:33.989385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66aa60d037af'
down_revision = '1b0976cbe4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TOUR', sa.Column('category', sa.Enum('ANIMALS', 'BEACH', 'FOODANDDRINK', 'HIKING', 'CITY', name='tourcategory'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TOUR', 'category')
    # ### end Alembic commands ###
