"""empty message

Revision ID: 72f025984061
Revises: a51fb41ba42e
Create Date: 2020-05-20 19:33:25.925265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72f025984061'
down_revision = 'a51fb41ba42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LOCATION',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('address', sa.String(length=60), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['TOUR.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('TOUR_LOCATION')
    op.create_unique_constraint(None, 'TOUR_IMAGE', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TOUR_IMAGE', type_='unique')
    op.create_table('TOUR_LOCATION',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"TOUR_LOCATION_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('tour_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['TOUR.uuid'], name='TOUR_LOCATION_tour_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='TOUR_LOCATION_pkey')
    )
    op.drop_table('LOCATION')
    # ### end Alembic commands ###
