"""empty message

Revision ID: 7b3a25d5ff7a
Revises: 66aa60d037af
Create Date: 2020-04-01 14:22:50.968818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3a25d5ff7a'
down_revision = '66aa60d037af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TOUR', sa.Column('category', sa.Enum('ANIMALS', 'BEACH', 'FOODANDDRINK', 'HIKING', 'CITY', name='tourcategory'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TOUR', 'category')
    # ### end Alembic commands ###
