"""empty message

Revision ID: 7b827f66eb2f
Revises: a5bf65231d3a
Create Date: 2020-04-01 20:09:47.195220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b827f66eb2f'
down_revision = 'a5bf65231d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('REVIEWS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('reviewee_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('review_type', sa.Enum('GUIDE', 'CUSTOMER', name='reviewtype'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewee_id'], ['USER.uuid'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['USER.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('REVIEWS')
    # ### end Alembic commands ###
