"""empty message

Revision ID: 836d36e4e081
Revises: 72f025984061
Create Date: 2020-05-20 19:41:23.898839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '836d36e4e081'
down_revision = '72f025984061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('LOCATION_tour_id_fkey', 'LOCATION', type_='foreignkey')
    op.drop_column('LOCATION', 'tour_id')
    op.add_column('TOUR', sa.Column('category', sa.ARRAY(sa.Enum('ANIMALS', 'BEACH', 'FOODANDDRINK', 'HIKING', 'CITY', name='tourcategory')), nullable=True))
    op.add_column('TOUR', sa.Column('location', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'TOUR', 'LOCATION', ['location'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TOUR', type_='foreignkey')
    op.drop_column('TOUR', 'location')
    op.drop_column('TOUR', 'category')
    op.add_column('LOCATION', sa.Column('tour_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('LOCATION_tour_id_fkey', 'LOCATION', 'TOUR', ['tour_id'], ['uuid'])
    # ### end Alembic commands ###
