"""empty message

Revision ID: 8dfa36dddd77
Revises: aee59ca73cc9
Create Date: 2020-04-01 18:59:57.630417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfa36dddd77'
down_revision = 'aee59ca73cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('primary_image_constraint', 'TOUR_IMAGE', ['primary', 'tour_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('primary_image_constraint', 'TOUR_IMAGE', type_='unique')
    # ### end Alembic commands ###
