"""empty message

Revision ID: 8e9c45ee61ea
Revises: 725b10301c9d
Create Date: 2020-05-29 19:31:10.370040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9c45ee61ea'
down_revision = '725b10301c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('REVIEW', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('REVIEW', 'date_created')
    # ### end Alembic commands ###
