"""empty message

Revision ID: ac23a5a40ba9
Revises: 61873da3309a
Create Date: 2020-05-26 21:56:28.308093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac23a5a40ba9'
down_revision = '61873da3309a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IMAGE', sa.Column('url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('IMAGE', 'url')
    # ### end Alembic commands ###
