"""empty message

Revision ID: c2c8170be46f
Revises: ac23a5a40ba9
Create Date: 2020-05-26 22:00:16.757520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2c8170be46f'
down_revision = 'ac23a5a40ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IMAGE')
    op.add_column('TOUR', sa.Column('image_url', sa.Text(), nullable=True))
    op.drop_constraint('TOUR_image_id_fkey', 'TOUR', type_='foreignkey')
    op.drop_column('TOUR', 'image_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TOUR', sa.Column('image_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('TOUR_image_id_fkey', 'TOUR', 'IMAGE', ['image_id'], ['uuid'])
    op.drop_column('TOUR', 'image_url')
    op.create_table('IMAGE',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v1()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='IMAGE_pkey'),
    sa.UniqueConstraint('uuid', name='IMAGE_uuid_key')
    )
    # ### end Alembic commands ###
