"""empty message

Revision ID: c7739a5ea109
Revises: dd920fb6ef26
Create Date: 2020-03-31 16:11:20.750668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7739a5ea109'
down_revision = 'dd920fb6ef26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('LOCATION_tour_id_fkey', 'LOCATION', type_='foreignkey')
    op.create_foreign_key(None, 'LOCATION', 'TOUR', ['tour_id'], ['uuid'])
    op.drop_constraint('TOUR_guide_id_fkey', 'TOUR', type_='foreignkey')
    op.create_foreign_key(None, 'TOUR', 'USER', ['guide_id'], ['uuid'])
    op.drop_column('TOUR', 'id')
    op.drop_constraint('TOUR_DATE_tour_id_fkey', 'TOUR_DATE', type_='foreignkey')
    op.create_foreign_key(None, 'TOUR_DATE', 'TOUR', ['tour_id'], ['uuid'])
    op.drop_constraint('TOUR_IMAGE_tour_id_fkey', 'TOUR_IMAGE', type_='foreignkey')
    op.create_foreign_key(None, 'TOUR_IMAGE', 'TOUR', ['tour_id'], ['uuid'])
    op.drop_column('USER', 'id')
    op.drop_constraint('VERNACULAR_user_id_fkey', 'VERNACULAR', type_='foreignkey')
    op.create_foreign_key(None, 'VERNACULAR', 'USER', ['user_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'VERNACULAR', type_='foreignkey')
    op.create_foreign_key('VERNACULAR_user_id_fkey', 'VERNACULAR', 'USER', ['user_id'], ['id'])
    op.add_column('USER', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"USER_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'TOUR_IMAGE', type_='foreignkey')
    op.create_foreign_key('TOUR_IMAGE_tour_id_fkey', 'TOUR_IMAGE', 'TOUR', ['tour_id'], ['id'])
    op.drop_constraint(None, 'TOUR_DATE', type_='foreignkey')
    op.create_foreign_key('TOUR_DATE_tour_id_fkey', 'TOUR_DATE', 'TOUR', ['tour_id'], ['id'])
    op.add_column('TOUR', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"TOUR_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'TOUR', type_='foreignkey')
    op.create_foreign_key('TOUR_guide_id_fkey', 'TOUR', 'USER', ['guide_id'], ['id'])
    op.drop_constraint(None, 'LOCATION', type_='foreignkey')
    op.create_foreign_key('LOCATION_tour_id_fkey', 'LOCATION', 'TOUR', ['tour_id'], ['id'])
    # ### end Alembic commands ###
