"""empty message

Revision ID: d2cd9474768a
Revises: 1a173257901a
Create Date: 2020-04-01 14:12:10.827490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cd9474768a'
down_revision = '1a173257901a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TOUR_IMAGE', sa.Column('category', sa.Enum('ANIMALS', 'BEACH', 'FOODANDDRINK', 'HIKING', 'CITY', name='tourcategory'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TOUR_IMAGE', 'category')
    # ### end Alembic commands ###
