"""empty message

Revision ID: d9a8a0628522
Revises: 41cddfa95837
Create Date: 2020-05-20 20:18:51.542711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9a8a0628522'
down_revision = '41cddfa95837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TOUR', 'category',
               existing_type=postgresql.ENUM('ANIMALS', 'BEACH', 'FOODANDDRINK', 'HIKING', 'CITY', name='tourcategory'),
               nullable=False)
    op.alter_column('TOUR', 'location',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TOUR', 'location',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('TOUR', 'category',
               existing_type=postgresql.ENUM('ANIMALS', 'BEACH', 'FOODANDDRINK', 'HIKING', 'CITY', name='tourcategory'),
               nullable=True)
    # ### end Alembic commands ###
