"""empty message

Revision ID: e2d3076e6f33
Revises: 4f92c48f6ffd
Create Date: 2020-04-01 15:21:50.543970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d3076e6f33'
down_revision = '4f92c48f6ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'TOUR', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TOUR', type_='unique')
    # ### end Alembic commands ###
