"""empty message

Revision ID: f7e429e4f539
Revises: 1eb2c380e310
Create Date: 2020-05-29 15:06:37.347649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e429e4f539'
down_revision = '1eb2c380e310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('location', sa.Text(), nullable=True))
    op.drop_constraint('USER_location_id_fkey', 'USER', type_='foreignkey')
    op.drop_column('USER', 'location_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('USER_location_id_fkey', 'USER', 'LOCATION', ['location_id'], ['id'])
    op.drop_column('USER', 'location')
    # ### end Alembic commands ###
